baseURL = "http://localhost"
languageCode = "en-us"
title = "PyCon India 2020 | September 17th to 20th"

[params]
    description = "PyCon India is the largest gathering of Pythonistas in India for the Python programming language."
